### ISSUE TITLE
Power consumption is constantly 0.0 W

### ISSUE THREAD

**Issue by ViBE-HU** [Pijuli/GnomePowerTracker#3]
I'm on Ubuntu 24.04. The system is up to date. Let me know what information you need.

**Comment by Pijuli** [comment]
Hi! Would you mind asking some questions?

- are you using a laptop?
- do you have more than one battery?
- check this path, if it exists, and let me know what files are in it

/sys/class/power_supply/BAT0

Cheers!

**Comment by ViBE-HU** [comment]
Yes, it is a [Lenovo Legion 5 15ACH6H](https://psref.lenovo.com/syspool/Sys/PDF/Legion/Lenovo_Legion_5_15ACH6H/Lenovo_Legion_5_15ACH6H_Spec.pdf). It has a single built in battery. The command's output says that it BAT0 is a directory.

**Comment by 3ship** [comment]
I'm experiencing the same on an Acer Swift 314 with EndeavourOS. As far as I'm aware, this model only has one battery.

`BAT0` doesn't exist. But `BAT1` does.

`upower` and `powertop` can display the battery power usage.

**Comment by Pijuli** [comment]
> Yes, it is a [Lenovo Legion 5 15ACH6H](https://psref.lenovo.com/syspool/Sys/PDF/Legion/Lenovo_Legion_5_15ACH6H/Lenovo_Legion_5_15ACH6H_Spec.pdf). It has a single built in battery. The command's output says that `BAT0` is a directory.

What files are in it??

**Comment by Pijuli** [comment]
> I'm experiencing the same on an Acer Swift 314 with EndeavourOS. As far as I'm aware, this model only has one battery.
> 
> `BAT0` doesn't exist. But `BAT1` does.
> 
> `upower` and `powertop` can display the battery power usage.

Yes, that could happen. If you are in a hurry to use it, you can edit the code and point to the right directory. I'll dig into it this week. Would you mind opening a new issue regarding manual battery configuration? Didn't expect it to popup that soon

**Comment by 3ship** [comment]
I haven't manually reconfigured anything. Based on some [old threads](https://askubuntu.com/questions/69556/how-do-i-check-the-batterys-status-via-the-terminal) I've found, this seems to be related to Arch Linux still starting from BAT1 as the default.

**Comment by Pijuli** [comment]
> I haven't manually reconfigured anything. Based on some [old threads](https://askubuntu.com/questions/69556/how-do-i-check-the-batterys-status-via-the-terminal) I've found, this seems to be related to Arch Linux still starting from BAT1 as the default.

I know you didn't. It's funny how my endeavourOS works with BAT0... 🤦
Give me some days. I'll let you know!

**Comment by janvlug** [comment]
Confirming on a Fedora 40 laptop.

**Comment by Novantric** [comment]
Same issue as me. Maybe add a simple dialogue to select a battery?
![image](https://github.com/user-attachments/assets/10a25cd0-0576-4113-8e2c-065c4952d0a3)

**Comment by Pijuli** [comment]
> Same issue as me. Maybe add a simple dialogue to select a battery? ![image](https://private-user-images.githubusercontent.com/53978071/369717866-10a25cd0-0576-4113-8e2c-065c4952d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDE2NzQsIm5iZiI6MTcyNzA0MTM3NCwicGF0aCI6Ii81Mzk3ODA3MS8zNjk3MTc4NjYtMTBhMjVjZDAtMDU3Ni00MTEzLThlMmMtMDY1YzQ5NTJkMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDIxNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyODlkYzY5MDI1MjkxYjMyNmNiZGMxMzlhYmZlNWZiNjQ5YjQwMTRlN2M3ZDE3MzE1YzNlMWQ3MjBkNDZlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PqCt0mTHLhxr9D39IChjeVFMyiKKzpcTkM7V9G0j6ZM)

Still, I need to see what's inside your folders. Yet, your case has also been taking in account. wtf "BATT" alone 🤣
I will be pushing an update to autodetect the folder today.
Later, I will provide some configurable params

**Comment by Pijuli** [comment]
This should fix the issues

https://github.com/Pijuli/GnomePowerTracker/pull/5

I'll let you know and close the issue when it's published

**Comment by Pijuli** [comment]
Already published. You can check now

**Comment by ViBE-HU** [comment]
> > Yes, it is a [Lenovo Legion 5 15ACH6H](https://psref.lenovo.com/syspool/Sys/PDF/Legion/Lenovo_Legion_5_15ACH6H/Lenovo_Legion_5_15ACH6H_Spec.pdf). It has a single built in battery. The command's output says that `BAT0` is a directory.
> 
> What files are in it??

```
alarm
capacity
capacity_level
cycle_count
energy_full
energy_full_design
energy_now
manufacturer
model_name
power_now
present
serial_number
status
technology
type
uevent
voltage_min_design
voltage_now
```

**Comment by Pijuli** [comment]
That should be working, actually.
can you cat power_now file?

**Comment by ViBE-HU** [comment]
> That should be working, actually. Can you cat power_now file? Have you tried updating the extension already?

Yes, the update was done.
```
$ cat power_now
0
```

**Comment by Pijuli** [comment]
> > That should be working, actually. Can you cat power_now file? Have you tried updating the extension already?
> 
> Yes, the update was done.
> 
> ```
> $ cat power_now
> 0
> ```

Then... I'm sorry but if your acpi reports 0mW I have not much to do 😅
Stupid question, did you unplug the charger? 🙈

Yet, if you find the power reported somewhere else we can look into it and find a fix. 
I'll keep the issue open, let me know

**Comment by ViBE-HU** [comment]
> > > That should be working, actually. Can you cat power_now file? Have you tried updating the extension already?
> > 
> > 
> > Yes, the update was done.
> > ```
> > $ cat power_now
> > 0
> > ```
> 
> Then... I'm sorry but if your acpi reports 0mW I have not much to do 😅 Stupid question, did you unplug the charger? 🙈
> 
> Yet, if you find the power reported somewhere else we can look into it and find a fix. I'll keep the issue open, let me know

LOL it was not a stupid question. It works when I unplug the charger. But based on the description I thought the extension measures consumption in general not just the battery.

**Comment by Pijuli** [comment]
Nope! It measures the input and the output of the battery!! If it's full, it's 0W.
Sorry if it was not clear 😅😅😅
