### ISSUE TITLE
Use minus sign glyph instead of hyphen

### ISSUE THREAD

**Issue by uwe-ss** [Pijuli/GnomePowerTracker#4]
GNOME loves to be typographically correct, of course especially when it comes to onscreen elements that are shown permanently. So I would suggest to use the real minus sign glyph (2212) instead of a hyphen when indicating negative values.

 There are differences, really! In vertical alignment, width, stroke, and distance to the next glyph. Basically, the minus sign harmonizes with the plus sign and the digits. The hyphen does not.

I think a fork is not necessary.

**Comment by ViBE-HU** [comment]
Also it would be nice to let the extension use the correct separator which match with the system's language.

**Comment by Pijuli** [comment]
> GNOME loves to be typographically correct, of course especially when it comes to onscreen elements that are shown permanently. So I would suggest to use the real minus sign glyph (2212) instead of a hyphen when indicating negative values.
> 
>  There are differences, really! In vertical alignment, width, stroke, and distance to the next glyph. Basically, the minus sign harmonizes with the plus sign and the digits. The hyphen does not.
> 
> I think a fork is not necessary.

Will do this week. Thanks for letting me know

**Comment by Pijuli** [comment]
> Also it would be nice to let the extension use the correct separator which match with the system's language.

I'll try my best. Bear in mind it is my first extension and I don't know literally nothing about how to retrieve the language separator
Cheers!

**Comment by ViBE-HU** [comment]
> > Also it would be nice to let the extension use the correct separator which match with the system's language.
> 
> I'll try my best. Bear in mind it is my first extension and I know literally nothing about how to retrieve the language separator Cheers!

Of course. It is just suggestion, not a judgement.

**Comment by uwe-ss** [comment]
Regarding the localized decimal mark: Maybe the standard JavaScript function "toLocaleString" will do it for us.

**Comment by Pijuli** [comment]
This should fix both issues

https://github.com/Pijuli/GnomePowerTracker/pull/5

I'll let you know and close the issue when it's published

**Comment by uwe-ss** [comment]
For me, everything looks fine!

(If it comes to a settings GUI and you decide to make it localizable I would be glad to provide the German language version.)

**Comment by Pijuli** [comment]
Awesome. I might look into it this week. Let's see how it goes.
Btw, extension is already published, you can update it already from Gnome Extensions app
